stages:
- mavenbuild
- maventest
- autodeploy

maven-build:
    stage: mavenbuild
    tags:
    - shell
    script:
    - cd ./backend/code
    - mvn package -B

maven-test:
    stage: maventest
    tags:
    - shell
    script:
    - cd ./backend/code
    - mvn test
    artifacts:
        paths:
        - ./backend/code/target/*.jar
