stages:
- mavenbuild
- maventest
- autodeploy
- androidbuild


maven-build:
    stage: mavenbuild
    tags:
    - shell
    script:
    - cd /home/2_do_4/backend/code
    - sudo mvn package -B

maven-test:
    stage: maventest
    tags:
    - shell
    script:
    - cd /home/2_do_4/backend/code
    - sudo mvn test
    artifacts:
        paths:
        - /home/2_do_4/backend/code/target/*.jar

auto-deployment:
    stage: autodeploy
    tags:
    - shell
    script:
    - cd /home/2_do_4/backend/code
    - sudo mvn clean
    - sudo mvn package
    - sudo mv ./target/*.jar /target/cybuds-server.jar

android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x /home/2_do_4/frontend/androidApp/gradlew
    tags:
    - docker
    script:
    - cd /home/2_do_4/frontend/androidApp
    - ./gradlew assemble
    artifacts:
        paths:
        - /home/2_do_4/frontend/androidApp/app/build/outputs

