stages:
- mavenbuild
- maventest
- autodeploy
- androidbuild
- androidtest

maven-build:
    stage: mavenbuild
    tags:
    - shell
    script:
    - cd backend/code
    - sudo mvn package -B

maven-test:
    stage: maventest
    tags:
    - shell
    script:
    - cd backend/code
    - sudo mvn test
    artifacts:
        paths:
        - "./*.jar"

auto-deployment:
    stage: autodeploy
    tags:
    - shell
    script:
    - cd backend/code
    - sudo mvn clean
    - sudo mvn package
    - sudo mv ./target/*.jar /target/cybuds-server.jar
    - sudo systemctl restart system-cybuds-server.service

android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x frontend/androidApp/gradlew
    tags:
    - docker
    script:
    - cd ./frontend/androidApp
    - ./gradlew assemble
    artifacts:
        paths:
        - ./frontend/androidApp/app/build/outputs

android-test:
    image: javiersantos/android-ci:latest
    stage: androidtest
    before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/androidApp/gradlew
    tags:
    - docker
    script:
    - cd ./frontend/androidApp
    - ./gradlew test
