openapi: 3.0.3
info:
  title: Cybuds Server API
  description: Cybuds Server API
  version: 1.0.0
servers:
  - url: 'http://coms-309-028.cs.iastate.edu'
paths:
  /groups:
    get:
      summary: "GET groups"
      operationId: "retrieveAll"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST groups"
      operationId: "addGroup"
      responses:
        "200":
          description: "OK"
  /groups/{identifier}:
    get:
      summary: "GET groups/{identifier}"
      operationId: "getGroupByName"
      parameters:
        - name: "identifier"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
  /groups/{id}:
    put:
      summary: "PUT groups/{id}"
      operationId: "updateGroup"
      parameters:
        - name: "id"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE groups/{id}"
      operationId: "deleteGroup"
      parameters:
        - name: "id"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
  /interests:
    get:
      summary: "GET interests"
      operationId: "retrieveAll"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST interests"
      operationId: "addInterest"
      responses:
        "200":
          description: "OK"
  /interests/{identifier}:
    get:
      summary: "GET interests/{identifier}"
      operationId: "getInterestByName"
      parameters:
        - name: "identifier"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
  /interests/{id}:
    put:
      summary: "PUT interests/{id}"
      operationId: "updateGroup"
      parameters:
        - name: "id"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE interests/{id}"
      operationId: "deleteInterest"
      parameters:
        - name: "id"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
  /login:
    post:
      summary: "POST login"
      operationId: "stageLogin"
      responses:
        "200":
          description: "OK"
  /users:
    get:
      summary: "GET users"
      operationId: "getAllUsers"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST users"
      operationId: "addUser"
      responses:
        "200":
          description: "OK"
  /users/groups:
    get:
      summary: "GET users/groups"
      operationId: "getAllGroupsForUser"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST users/groups"
      operationId: "addRelation"
      parameters:
        - name: "user_id"
          in: "query"
          required: true
          schema:
            type: "number"
            format: "int64"
        - name: "group_id"
          in: "query"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        "200":
          description: "OK"
  /users/interests:
    get:
      summary: "GET users/interests"
      operationId: "getAllInterestsForUser"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST users/interests"
      operationId: "addRelation"
      parameters:
        - name: "user_id"
          in: "query"
          required: true
          schema:
            type: "number"
            format: "int64"
        - name: "interest_id"
          in: "query"
          required: true
          schema:
            type: "number"
            format: "int64"
      responses:
        "200":
          description: "OK"
  /users/{id}:
    get:
      summary: "GET users/{id}"
      operationId: "getUser"
      parameters:
        - name: "id"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
    put:
      summary: "PUT users/{id}"
      operationId: "updateUser"
      parameters:
        - name: "id"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE users/{id}"
      operationId: "deleteUser"
      parameters:
        - name: "id"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"
  /users/{username}:
    get:
      summary: "GET users/{username}"
      operationId: "getUser"
      parameters:
        - name: "username"
          in: "path"
          required: true
      responses:
        "200":
          description: "OK"